# Generated by Django 5.2.17 on 2026-08-10 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("PULL_REST", "Pull REST"),
                            ("PULL_GRAPHQL", "Pull GraphQL"),
                            ("WEBSOCKET", "WebSocket"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caller", models.CharField(max_length=100)),
                ("bytes_transferred", models.IntegerField(default=0)),
                ("record_count", models.IntegerField(default=0)),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="configs.template",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
