// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://..\\backend\\schema\\openapi.json` | (string & {});
};

export type AppSetting = {
    readonly id: number;
    key: string;
    value?: unknown;
    readonly updated_at: string;
};

export type AppSettingRequest = {
    key: string;
    value?: unknown;
};

export type AuditLog = {
    readonly id: number;
    readonly transaction_id: string;
    mode: ModeEnum;
    readonly caller: string;
    readonly bytes_transferred: number;
    readonly record_count: number;
    readonly status: string;
    readonly timestamp: string;
    readonly payload_json: unknown;
    readonly endpoint: string | null;
    readonly template: number | null;
};

export type Connection = {
    readonly id: number;
    name: string;
    url?: string | null;
    json_content?: string | null;
    is_local_file?: boolean;
    local_file_path?: string | null;
    update_interval_hours?: number;
    is_active?: boolean;
    connection_type?: ConnectionTypeEnum;
    sync_schedule?: string | null;
    environments?: unknown;
    auth_type?: ConnectionAuthTypeEnum;
    auth_config?: unknown;
    custom_headers?: unknown;
    schema_source?: SchemaSourceEnum;
    spec_auth_type?: ConnectionAuthTypeEnum;
    spec_auth_config?: unknown;
    spec_custom_headers?: unknown;
    auth_token?: string | null;
    readonly last_updated: string;
    readonly created_at: string;
};

/**
 * * `none` - None
 * * `bearer` - Bearer Token
 * * `api_key` - API Key
 * * `basic` - Basic Auth
 */
export type ConnectionAuthTypeEnum = 'none' | 'bearer' | 'api_key' | 'basic';

export type ConnectionRequest = {
    name: string;
    url?: string | null;
    json_content?: string | null;
    is_local_file?: boolean;
    local_file_path?: string | null;
    update_interval_hours?: number;
    is_active?: boolean;
    connection_type?: ConnectionTypeEnum;
    sync_schedule?: string | null;
    environments?: unknown;
    auth_type?: ConnectionAuthTypeEnum;
    auth_config?: unknown;
    custom_headers?: unknown;
    schema_source?: SchemaSourceEnum;
    spec_auth_type?: ConnectionAuthTypeEnum;
    spec_auth_config?: unknown;
    spec_custom_headers?: unknown;
    auth_token?: string | null;
};

/**
 * * `rest` - REST
 * * `graphql` - GraphQL
 */
export type ConnectionTypeEnum = 'rest' | 'graphql';

/**
 * * `push` - Push
 * * `pull_rest` - Pull REST
 * * `pull_graphql` - Pull GraphQL
 */
export type ExecutionModeEnum = 'push' | 'pull_rest' | 'pull_graphql';

export type FailedPayload = {
    readonly id: number;
    readonly job: number;
    readonly template: number;
    payload_json?: unknown;
    readonly error_message: string | null;
    readonly timestamp: string;
};

export type Health = {
    status: string;
};

export type Job = {
    readonly id: number;
    template: number;
    readonly template_name: string;
    template_detail: Template;
    schedule_interval?: number;
    is_active?: boolean;
    readonly last_run: string | null;
    readonly last_status: string | null;
    readonly created_at: string;
    readonly updated_at: string;
};

export type JobLog = {
    readonly id: number;
    readonly job: number;
    readonly timestamp: string;
    status: StatusEnum;
    readonly http_status: number | null;
    readonly error_message: string | null;
    payload_json?: unknown;
};

export type JobRequest = {
    template: number;
    schedule_interval?: number;
    is_active?: boolean;
};

export type Liveness = {
    status: string;
};

export type Metrics = {
    templates: unknown;
    jobs: unknown;
    logs: unknown;
};

/**
 * * `PUSH` - Push
 * * `PULL_REST` - Pull REST
 * * `PULL_GRAPHQL` - Pull GraphQL
 * * `WEBSOCKET` - WebSocket
 */
export type ModeEnum = 'PUSH' | 'PULL_REST' | 'PULL_GRAPHQL' | 'WEBSOCKET';

export type PaginatedAppSettingList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AppSetting>;
};

export type PaginatedAuditLogList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AuditLog>;
};

export type PaginatedConnectionList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Connection>;
};

export type PaginatedFailedPayloadList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<FailedPayload>;
};

export type PaginatedJobList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Job>;
};

export type PaginatedJobLogList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<JobLog>;
};

export type PaginatedTemplateList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Template>;
};

export type PatchedAppSettingRequest = {
    key?: string;
    value?: unknown;
};

export type PatchedConnectionRequest = {
    name?: string;
    url?: string | null;
    json_content?: string | null;
    is_local_file?: boolean;
    local_file_path?: string | null;
    update_interval_hours?: number;
    is_active?: boolean;
    connection_type?: ConnectionTypeEnum;
    sync_schedule?: string | null;
    environments?: unknown;
    auth_type?: ConnectionAuthTypeEnum;
    auth_config?: unknown;
    custom_headers?: unknown;
    schema_source?: SchemaSourceEnum;
    spec_auth_type?: ConnectionAuthTypeEnum;
    spec_auth_config?: unknown;
    spec_custom_headers?: unknown;
    auth_token?: string | null;
};

export type PatchedJobRequest = {
    template?: number;
    schedule_interval?: number;
    is_active?: boolean;
};

export type PatchedTemplateRequest = {
    name?: string;
    execution_mode?: ExecutionModeEnum;
    pull_method?: string;
    partner_url?: string | null;
    partner_auth_token?: string | null;
    sources?: unknown;
    client_name?: string | null;
    client_url?: string | null;
    client_auth_type?: string;
    client_credentials?: unknown;
    destinations?: unknown;
};

export type Readiness = {
    status: string;
    database?: string;
};

/**
 * * `introspection` - Introspection
 * * `upload` - Upload
 */
export type SchemaSourceEnum = 'introspection' | 'upload';

/**
 * * `SUCCESS` - Success
 * * `FAILED` - Failed
 */
export type StatusEnum = 'SUCCESS' | 'FAILED';

export type Template = {
    readonly id: number;
    name: string;
    readonly slug: string;
    execution_mode?: ExecutionModeEnum;
    pull_method?: string;
    partner_url?: string | null;
    partner_auth_token?: string | null;
    sources: unknown;
    client_name?: string | null;
    client_url?: string | null;
    client_auth_type?: string;
    client_credentials?: unknown;
    destinations?: unknown;
    readonly created_at: string;
    readonly updated_at: string;
};

export type TemplateRequest = {
    name: string;
    execution_mode?: ExecutionModeEnum;
    pull_method?: string;
    partner_url?: string | null;
    partner_auth_token?: string | null;
    sources: unknown;
    client_name?: string | null;
    client_url?: string | null;
    client_auth_type?: string;
    client_credentials?: unknown;
    destinations?: unknown;
};

export type AppSettingWritable = {
    key: string;
    value?: unknown;
};

export type ConnectionWritable = {
    name: string;
    url?: string | null;
    json_content?: string | null;
    is_local_file?: boolean;
    local_file_path?: string | null;
    update_interval_hours?: number;
    is_active?: boolean;
    connection_type?: ConnectionTypeEnum;
    sync_schedule?: string | null;
    environments?: unknown;
    auth_type?: ConnectionAuthTypeEnum;
    auth_config?: unknown;
    custom_headers?: unknown;
    schema_source?: SchemaSourceEnum;
    spec_auth_type?: ConnectionAuthTypeEnum;
    spec_auth_config?: unknown;
    spec_custom_headers?: unknown;
    auth_token?: string | null;
};

export type FailedPayloadWritable = {
    payload_json?: unknown;
};

export type JobWritable = {
    template: number;
    schedule_interval?: number;
    is_active?: boolean;
};

export type JobLogWritable = {
    payload_json?: unknown;
};

export type PaginatedAppSettingListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AppSettingWritable>;
};

export type PaginatedAuditLogListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedConnectionListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ConnectionWritable>;
};

export type PaginatedFailedPayloadListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<FailedPayloadWritable>;
};

export type PaginatedJobListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<JobWritable>;
};

export type PaginatedJobLogListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<JobLogWritable>;
};

export type PaginatedTemplateListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<TemplateWritable>;
};

export type TemplateWritable = {
    name: string;
    execution_mode?: ExecutionModeEnum;
    pull_method?: string;
    partner_url?: string | null;
    partner_auth_token?: string | null;
    sources: unknown;
    client_name?: string | null;
    client_url?: string | null;
    client_auth_type?: string;
    client_credentials?: unknown;
    destinations?: unknown;
};

export type ApiV1AuditLogsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/audit-logs/';
};

export type ApiV1AuditLogsListResponses = {
    200: PaginatedAuditLogList;
};

export type ApiV1AuditLogsListResponse = ApiV1AuditLogsListResponses[keyof ApiV1AuditLogsListResponses];

export type ApiV1AuditLogsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this audit log.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/audit-logs/{id}/';
};

export type ApiV1AuditLogsRetrieveResponses = {
    200: AuditLog;
};

export type ApiV1AuditLogsRetrieveResponse = ApiV1AuditLogsRetrieveResponses[keyof ApiV1AuditLogsRetrieveResponses];

export type ApiV1ConnectionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/connections/';
};

export type ApiV1ConnectionsListResponses = {
    200: PaginatedConnectionList;
};

export type ApiV1ConnectionsListResponse = ApiV1ConnectionsListResponses[keyof ApiV1ConnectionsListResponses];

export type ApiV1ConnectionsCreateData = {
    body: ConnectionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/connections/';
};

export type ApiV1ConnectionsCreateResponses = {
    201: Connection;
};

export type ApiV1ConnectionsCreateResponse = ApiV1ConnectionsCreateResponses[keyof ApiV1ConnectionsCreateResponses];

export type ApiV1ConnectionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/';
};

export type ApiV1ConnectionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiV1ConnectionsDestroyResponse = ApiV1ConnectionsDestroyResponses[keyof ApiV1ConnectionsDestroyResponses];

export type ApiV1ConnectionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/';
};

export type ApiV1ConnectionsRetrieveResponses = {
    200: Connection;
};

export type ApiV1ConnectionsRetrieveResponse = ApiV1ConnectionsRetrieveResponses[keyof ApiV1ConnectionsRetrieveResponses];

export type ApiV1ConnectionsPartialUpdateData = {
    body?: PatchedConnectionRequest;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/';
};

export type ApiV1ConnectionsPartialUpdateResponses = {
    200: Connection;
};

export type ApiV1ConnectionsPartialUpdateResponse = ApiV1ConnectionsPartialUpdateResponses[keyof ApiV1ConnectionsPartialUpdateResponses];

export type ApiV1ConnectionsUpdateData = {
    body: ConnectionRequest;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/';
};

export type ApiV1ConnectionsUpdateResponses = {
    200: Connection;
};

export type ApiV1ConnectionsUpdateResponse = ApiV1ConnectionsUpdateResponses[keyof ApiV1ConnectionsUpdateResponses];

export type ApiV1ConnectionsRefreshCreateData = {
    body: ConnectionRequest;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/refresh/';
};

export type ApiV1ConnectionsRefreshCreateResponses = {
    200: Connection;
};

export type ApiV1ConnectionsRefreshCreateResponse = ApiV1ConnectionsRefreshCreateResponses[keyof ApiV1ConnectionsRefreshCreateResponses];

export type ApiV1ConnectionsToggleCreateData = {
    body: ConnectionRequest;
    path: {
        /**
         * A unique integer value identifying this connection.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/connections/{id}/toggle/';
};

export type ApiV1ConnectionsToggleCreateResponses = {
    200: Connection;
};

export type ApiV1ConnectionsToggleCreateResponse = ApiV1ConnectionsToggleCreateResponses[keyof ApiV1ConnectionsToggleCreateResponses];

export type ApiV1FailedPayloadsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/failed-payloads/';
};

export type ApiV1FailedPayloadsListResponses = {
    200: PaginatedFailedPayloadList;
};

export type ApiV1FailedPayloadsListResponse = ApiV1FailedPayloadsListResponses[keyof ApiV1FailedPayloadsListResponses];

export type ApiV1FailedPayloadsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this failed payload.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/failed-payloads/{id}/';
};

export type ApiV1FailedPayloadsRetrieveResponses = {
    200: FailedPayload;
};

export type ApiV1FailedPayloadsRetrieveResponse = ApiV1FailedPayloadsRetrieveResponses[keyof ApiV1FailedPayloadsRetrieveResponses];

export type ApiV1HealthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/';
};

export type ApiV1HealthRetrieveResponses = {
    200: Health;
};

export type ApiV1HealthRetrieveResponse = ApiV1HealthRetrieveResponses[keyof ApiV1HealthRetrieveResponses];

export type ApiV1HealthLiveRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live/';
};

export type ApiV1HealthLiveRetrieveResponses = {
    200: Liveness;
};

export type ApiV1HealthLiveRetrieveResponse = ApiV1HealthLiveRetrieveResponses[keyof ApiV1HealthLiveRetrieveResponses];

export type ApiV1HealthReadyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready/';
};

export type ApiV1HealthReadyRetrieveResponses = {
    200: Readiness;
};

export type ApiV1HealthReadyRetrieveResponse = ApiV1HealthReadyRetrieveResponses[keyof ApiV1HealthReadyRetrieveResponses];

export type ApiV1JobLogsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/job-logs/';
};

export type ApiV1JobLogsListResponses = {
    200: PaginatedJobLogList;
};

export type ApiV1JobLogsListResponse = ApiV1JobLogsListResponses[keyof ApiV1JobLogsListResponses];

export type ApiV1JobLogsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this job log.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/job-logs/{id}/';
};

export type ApiV1JobLogsRetrieveResponses = {
    200: JobLog;
};

export type ApiV1JobLogsRetrieveResponse = ApiV1JobLogsRetrieveResponses[keyof ApiV1JobLogsRetrieveResponses];

export type ApiV1JobsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/jobs/';
};

export type ApiV1JobsListResponses = {
    200: PaginatedJobList;
};

export type ApiV1JobsListResponse = ApiV1JobsListResponses[keyof ApiV1JobsListResponses];

export type ApiV1JobsCreateData = {
    body: JobRequest;
    path?: never;
    query?: never;
    url: '/api/v1/jobs/';
};

export type ApiV1JobsCreateResponses = {
    201: Job;
};

export type ApiV1JobsCreateResponse = ApiV1JobsCreateResponses[keyof ApiV1JobsCreateResponses];

export type ApiV1JobsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this job.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/';
};

export type ApiV1JobsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiV1JobsDestroyResponse = ApiV1JobsDestroyResponses[keyof ApiV1JobsDestroyResponses];

export type ApiV1JobsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this job.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/';
};

export type ApiV1JobsRetrieveResponses = {
    200: Job;
};

export type ApiV1JobsRetrieveResponse = ApiV1JobsRetrieveResponses[keyof ApiV1JobsRetrieveResponses];

export type ApiV1JobsPartialUpdateData = {
    body?: PatchedJobRequest;
    path: {
        /**
         * A unique integer value identifying this job.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/';
};

export type ApiV1JobsPartialUpdateResponses = {
    200: Job;
};

export type ApiV1JobsPartialUpdateResponse = ApiV1JobsPartialUpdateResponses[keyof ApiV1JobsPartialUpdateResponses];

export type ApiV1JobsUpdateData = {
    body: JobRequest;
    path: {
        /**
         * A unique integer value identifying this job.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/';
};

export type ApiV1JobsUpdateResponses = {
    200: Job;
};

export type ApiV1JobsUpdateResponse = ApiV1JobsUpdateResponses[keyof ApiV1JobsUpdateResponses];

export type ApiV1JobsToggleCreateData = {
    body: JobRequest;
    path: {
        /**
         * A unique integer value identifying this job.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/jobs/{id}/toggle/';
};

export type ApiV1JobsToggleCreateResponses = {
    200: Job;
};

export type ApiV1JobsToggleCreateResponse = ApiV1JobsToggleCreateResponses[keyof ApiV1JobsToggleCreateResponses];

export type ApiV1JobsBulkToggleCreateData = {
    body: JobRequest;
    path?: never;
    query?: never;
    url: '/api/v1/jobs/bulk_toggle/';
};

export type ApiV1JobsBulkToggleCreateResponses = {
    200: Job;
};

export type ApiV1JobsBulkToggleCreateResponse = ApiV1JobsBulkToggleCreateResponses[keyof ApiV1JobsBulkToggleCreateResponses];

export type ApiV1MetricsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/metrics/';
};

export type ApiV1MetricsRetrieveResponses = {
    200: Metrics;
};

export type ApiV1MetricsRetrieveResponse = ApiV1MetricsRetrieveResponses[keyof ApiV1MetricsRetrieveResponses];

export type ApiV1SettingsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/settings/';
};

export type ApiV1SettingsListResponses = {
    200: PaginatedAppSettingList;
};

export type ApiV1SettingsListResponse = ApiV1SettingsListResponses[keyof ApiV1SettingsListResponses];

export type ApiV1SettingsCreateData = {
    body: AppSettingRequest;
    path?: never;
    query?: never;
    url: '/api/v1/settings/';
};

export type ApiV1SettingsCreateResponses = {
    201: AppSetting;
};

export type ApiV1SettingsCreateResponse = ApiV1SettingsCreateResponses[keyof ApiV1SettingsCreateResponses];

export type ApiV1SettingsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this app setting.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/settings/{id}/';
};

export type ApiV1SettingsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiV1SettingsDestroyResponse = ApiV1SettingsDestroyResponses[keyof ApiV1SettingsDestroyResponses];

export type ApiV1SettingsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this app setting.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/settings/{id}/';
};

export type ApiV1SettingsRetrieveResponses = {
    200: AppSetting;
};

export type ApiV1SettingsRetrieveResponse = ApiV1SettingsRetrieveResponses[keyof ApiV1SettingsRetrieveResponses];

export type ApiV1SettingsPartialUpdateData = {
    body?: PatchedAppSettingRequest;
    path: {
        /**
         * A unique integer value identifying this app setting.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/settings/{id}/';
};

export type ApiV1SettingsPartialUpdateResponses = {
    200: AppSetting;
};

export type ApiV1SettingsPartialUpdateResponse = ApiV1SettingsPartialUpdateResponses[keyof ApiV1SettingsPartialUpdateResponses];

export type ApiV1SettingsUpdateData = {
    body: AppSettingRequest;
    path: {
        /**
         * A unique integer value identifying this app setting.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/settings/{id}/';
};

export type ApiV1SettingsUpdateResponses = {
    200: AppSetting;
};

export type ApiV1SettingsUpdateResponse = ApiV1SettingsUpdateResponses[keyof ApiV1SettingsUpdateResponses];

export type ApiV1TemplatesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/v1/templates/';
};

export type ApiV1TemplatesListResponses = {
    200: PaginatedTemplateList;
};

export type ApiV1TemplatesListResponse = ApiV1TemplatesListResponses[keyof ApiV1TemplatesListResponses];

export type ApiV1TemplatesCreateData = {
    body: TemplateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/templates/';
};

export type ApiV1TemplatesCreateResponses = {
    201: Template;
};

export type ApiV1TemplatesCreateResponse = ApiV1TemplatesCreateResponses[keyof ApiV1TemplatesCreateResponses];

export type ApiV1TemplatesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Bridge Template.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/templates/{id}/';
};

export type ApiV1TemplatesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiV1TemplatesDestroyResponse = ApiV1TemplatesDestroyResponses[keyof ApiV1TemplatesDestroyResponses];

export type ApiV1TemplatesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Bridge Template.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/templates/{id}/';
};

export type ApiV1TemplatesRetrieveResponses = {
    200: Template;
};

export type ApiV1TemplatesRetrieveResponse = ApiV1TemplatesRetrieveResponses[keyof ApiV1TemplatesRetrieveResponses];

export type ApiV1TemplatesPartialUpdateData = {
    body?: PatchedTemplateRequest;
    path: {
        /**
         * A unique integer value identifying this Bridge Template.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/templates/{id}/';
};

export type ApiV1TemplatesPartialUpdateResponses = {
    200: Template;
};

export type ApiV1TemplatesPartialUpdateResponse = ApiV1TemplatesPartialUpdateResponses[keyof ApiV1TemplatesPartialUpdateResponses];

export type ApiV1TemplatesUpdateData = {
    body: TemplateRequest;
    path: {
        /**
         * A unique integer value identifying this Bridge Template.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/templates/{id}/';
};

export type ApiV1TemplatesUpdateResponses = {
    200: Template;
};

export type ApiV1TemplatesUpdateResponse = ApiV1TemplatesUpdateResponses[keyof ApiV1TemplatesUpdateResponses];
