# Generated by Django 5.2.17 on 2026-08-10 10:46

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull_rest", "Pull REST"),
                            ("pull_graphql", "Pull GraphQL"),
                        ],
                        default="push",
                        max_length=50,
                    ),
                ),
                ("pull_method", models.CharField(default="GET", max_length=10)),
                (
                    "partner_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "partner_auth_token",
                    apps.core.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "sources",
                    apps.core.fields.EncryptedJSONField(blank=True, default=list),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("client_url", models.CharField(blank=True, max_length=255, null=True)),
                ("client_auth_type", models.CharField(default="none", max_length=50)),
                (
                    "client_credentials",
                    apps.core.fields.EncryptedJSONField(blank=True, default=dict),
                ),
                (
                    "destinations",
                    apps.core.fields.EncryptedJSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bridge Template",
                "verbose_name_plural": "Bridge Templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
