# Generated by Django 5.2.17 on 2026-08-10 12:09

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_template_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="Asia/Kolkata"),
        ),
    ]
