# Generated by Django 5.2.17 on 2026-08-10 10:46

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("json_content", models.TextField(blank=True, null=True)),
                ("is_local_file", models.BooleanField(default=False)),
                (
                    "local_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("update_interval_hours", models.IntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("rest", "REST"), ("graphql", "GraphQL")],
                        default="rest",
                        max_length=50,
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("environments", models.JSONField(blank=True, default=list)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer Token"),
                            ("api_key", "API Key"),
                            ("basic", "Basic Auth"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "auth_config",
                    apps.core.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "custom_headers",
                    apps.core.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "schema_source",
                    models.CharField(
                        choices=[
                            ("introspection", "Introspection"),
                            ("upload", "Upload"),
                        ],
                        default="introspection",
                        max_length=50,
                    ),
                ),
                (
                    "spec_auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer Token"),
                            ("api_key", "API Key"),
                            ("basic", "Basic Auth"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "spec_auth_config",
                    apps.core.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "spec_custom_headers",
                    apps.core.fields.EncryptedJSONField(blank=True, null=True),
                ),
                (
                    "auth_token",
                    apps.core.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
